apiVersion: v1
metadata:
  name: Playwright and Jest Sauce Labs
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - ./test/
image:
  base: saucelabs/sauce-playwright
  version: 1.0.0-saucectl0.5.0
sauce:
  region: eu-central-1
