apiVersion: v1
metadata:
  name: Playwright and Jest Sauce Labs
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - ./test/
image:
  base: saucelabs/stt-playwright-jest-node
  version: v0.1.3
sauce:
  region: eu-central-1
