
apiVersion: v1
metadata:
  name: TestCafe with Sauce Testrunner Toolkit
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - ./tests/
image:
  base: saucelabs/sauce-testcafe
  version: 1.8.5-saucectl0.6.3
sauce:
  region: eu-central-1
