
apiVersion: v1
metadata:
  name: TestCafe with Sauce Testrunner Toolkit
  tags:
    - e2e
    - release team
    - other tag
  build: Release $CI_COMMIT_SHORT_SHA
files:
  - ./tests/
image:
  base: saucelabs/stt-testcafe-node
  version: v0.1.2
sauce:
  region: eu-central-1
